qpup:
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 100

  joint_group_position_controller:
      type: position_controllers/JointTrajectoryController
      joints:
          - lf_hip_joint
          - lf_upper_leg_joint
          - lf_lower_leg_joint
          - rf_hip_joint
          - rf_upper_leg_joint
          - rf_lower_leg_joint
          - lh_hip_joint
          - lh_upper_leg_joint
          - lh_lower_leg_joint
          - rh_hip_joint
          - rh_upper_leg_joint
          - rh_lower_leg_joint
