qpup:
  joints_list: &shared_joints_list
    - FLS
    - FLH
    - FLK
    - FRS
    - FRH
    - FRK
    - RLS
    - RLH
    - RLK
    - RRS
    - RRH
    - RRK

  joint_state_controller:
    type: joint_state_controller/JointStateController
    joints: *shared_joints_list
    publish_rate: 50

  odrive_state_controller:
    type: odrive_state_controller/OdriveStateController
    joints: *shared_joints_list
    publish_rate: 50

  imu_sensor_controller:
    type: imu_sensor_controller/ImuSensorController
    publish_rate: 50

  joint_group_position_controller: # Note: Can't change name because CHAMP hardcodes in some nodes
    type: position_controllers/JointTrajectoryController
    joints: *shared_joints_list
    publish_rate: 50

  joint_position_controllers:
    type: position_controllers/JointGroupPositionController
    joints joints: *shared_joints_list
    publish_rate: 50
