qpup:
  qpup_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  odrive_state_controller:
    type: odrive_state_controller/OdriveStateController
    publish_rate: 50
  imu_sensor_controller:
    type: imu_sensor_controller/ImuSensorController
    publish_rate: 50
