left_front:
  - FLS
  - FLH
  - FLK
  - lf_foot_joint

right_front:
  - FRS
  - FRH
  - FRK
  - rf_foot_joint

left_hind:
  - RLS
  - RLH
  - RLK
  - lh_foot_joint

right_hind:
  - RRS
  - RRH
  - RRK
  - rh_foot_joint
