uint16 AXIS_STATE_UNDEFINED=0
uint16 AXIS_STATE_IDLE=1
uint16 AXIS_STATE_STARTUP_SEQUENCE=2
uint16 AXIS_STATE_FULL_CALIBRATION_SEQUENCE=3
uint16 AXIS_STATE_MOTOR_CALIBRATION=4
uint16 AXIS_STATE_ENCODER_INDEX_SEARCH=6
uint16 AXIS_STATE_ENCODER_OFFSET_CALIBRATION=7
uint16 AXIS_STATE_CLOSED_LOOP_CONTROL=8
uint16 AXIS_STATE_LOCKIN_SPIN=9
uint16 AXIS_STATE_ENCODER_DIR_FIND=10
uint16 AXIS_STATE_HOMING=11
uint16 AXIS_STATE_ENCODER_HALL_POLARITY_CALIBRATION=12
uint16 AXIS_STATE_ENCODER_HALL_PHASE_CALIBRATION=13
uint16 AXIS_STATE_INVALID=14

string joint_name
uint16 axis_state
---
