uint16 INPUT_MODE_INACTIVE=0
uint16 INPUT_MODE_PASSTHROUGH=1
uint16 INPUT_MODE_VEL_RAMP=2
uint16 INPUT_MODE_POS_FILTER=3
uint16 INPUT_MODE_MIX_CHANNELS=4
uint16 INPUT_MODE_TRAP_TRAJ=5
uint16 INPUT_MODE_TORQUE_RAMP=6
uint16 INPUT_MODE_MIRROR=7
uint16 INPUT_MODE_TUNING=8
uint16 INPUT_MODE_INVALID=9

string joint_name
uint16 input_mode
---
