qpup:
  combined_robot_hw:
    shared_values:
      left_splay_transmission_reduction: &shared_left_splay_transmission_reduction 40.0 # TODO
      right_splay_transmission_reduction: &shared_right_splay_transmission_reduction 40.0 # TODO

      left_hip_transmission_reduction: &shared_left_hip_transmission_reduction 40.0
      left_hip_joint_offset: &shared_left_hip_joint_offset !degrees 45.0

      right_hip_transmission_reduction: &shared_right_hip_transmission_reduction -40.0
      right_hip_joint_offset: &shared_right_hip_joint_offset !degrees 45.0

      left_knee_transmission_reduction: &shared_left_knee_transmission_reduction -64.61538461538462
      left_knee_joint_offset: &shared_left_knee_joint_offset !degrees -90.0

      right_knee_transmission_reduction: &shared_right_knee_transmission_reduction 64.61538461538462
      right_knee_joint_offset: &shared_right_knee_joint_offset !degrees -90.0

    qpup_base:
      type: qpup_hw/QPUPHWReal

      joints:
        - name: FLS # Front Left Splay
          transmission_reduction: *shared_left_splay_transmission_reduction
          joint_offset: 0.0
          odrive_axis_can_node_id: 4
          pos_gain: 10.0
          vel_gain: 1.399999976158142
          vel_integrator_gain: 1.2000000476837158

        - name: FLH # Front Left Hip
          transmission_reduction: *shared_left_hip_transmission_reduction
          joint_offset: *shared_left_hip_joint_offset
          odrive_axis_can_node_id: 2
          pos_gain: 10.0
          vel_gain: 1.100000023841858
          vel_integrator_gain: 1.0

        - name: FLK # Front Left Knee
          transmission_reduction: *shared_left_knee_transmission_reduction
          joint_offset: *shared_left_knee_joint_offset
          odrive_axis_can_node_id: 1
          pos_gain: 10.0
          vel_gain: 1.5
          vel_integrator_gain: 1.0

        - name: FRS # Front Right Splay
          transmission_reduction: *shared_right_splay_transmission_reduction
          joint_offset: 0.0
          odrive_axis_can_node_id: 3
          pos_gain: 10.800000190734863
          vel_gain: 2.0
          vel_integrator_gain: 1.5

        - name: FRH # Front Right Hip
          transmission_reduction: *shared_right_hip_transmission_reduction
          joint_offset: *shared_right_hip_joint_offset
          odrive_axis_can_node_id: 6
          pos_gain: 10.350000381469727
          vel_gain: 1.399999976158142
          vel_integrator_gain: 1.3199999332427979

        - name: FRK # Front Right Knee
          transmission_reduction: *shared_right_knee_transmission_reduction
          joint_offset: *shared_right_knee_joint_offset
          odrive_axis_can_node_id: 5
          pos_gain: 10.0
          vel_gain: 1.0
          vel_integrator_gain: 1.0

        - name: RLS # Rear Left Splay
          transmission_reduction: *shared_left_splay_transmission_reduction
          joint_offset: 0.0
          odrive_axis_can_node_id: 9
          pos_gain: 6.0
          vel_gain: 1.9500000476837158
          vel_integrator_gain: 1.5

        - name: RLH # Rear Left Hip
          transmission_reduction: *shared_left_hip_transmission_reduction
          joint_offset: *shared_left_hip_joint_offset
          odrive_axis_can_node_id: 12
          pos_gain: 9.5
          vel_gain: 1.600000023841858
          vel_integrator_gain: 1.600000023841858

        - name: RLK # Rear Left Knee
          transmission_reduction: *shared_left_knee_transmission_reduction
          joint_offset: *shared_left_knee_joint_offset
          odrive_axis_can_node_id: 11
          pos_gain: 10.0
          vel_gain: 1.7999999523162842
          vel_integrator_gain: 3.299999952316284

        - name: RRS # Rear Right Splay
          transmission_reduction: *shared_right_splay_transmission_reduction
          joint_offset: 0.0
          odrive_axis_can_node_id: 10
          pos_gain: 6.0
          vel_gain: 1.9500000476837158
          vel_integrator_gain: 1.5

        - name: RRH # Rear Right Hip
          transmission_reduction: *shared_right_hip_transmission_reduction
          joint_offset: *shared_right_hip_joint_offset
          odrive_axis_can_node_id: 8
          pos_gain: 10.0
          vel_gain: 1.600000023841858
          vel_integrator_gain: 1.399999976158142

        - name: RRK # Rear Right Knee
          transmission_reduction: *shared_right_knee_transmission_reduction
          joint_offset: *shared_right_knee_joint_offset
          odrive_axis_can_node_id: 7
          pos_gain: 10.0
          vel_gain: 1.2000000476837158
          vel_integrator_gain: 3.299999952316284
