qpup:
  combined_robot_hw:
    shared_values:
      splay_transmission_reduction: &shared_splay_transmission_reduction 40.0
      hip_transmission_reduction: &shared_hip_transmission_reduction 40.0
      knee_transmission_reduction: &shared_knee_transmission_reduction 64.61538461538462

    qpup_base:
      type: qpup_hw/QPUPHWReal

      joints:
        - name: lf_hip_joint # FLS
          transmission_reduction: *shared_splay_transmission_reduction
          odrive_axis_can_node_id: 4

        - name: lf_upper_leg_joint # FLH
          transmission_reduction: *shared_hip_transmission_reduction
          odrive_axis_can_node_id: 2

        - name: lf_lower_leg_joint # FLK
          transmission_reduction: *shared_knee_transmission_reduction
          odrive_axis_can_node_id: 1

        - name: rf_hip_joint # FRS
          transmission_reduction: *shared_splay_transmission_reduction
          odrive_axis_can_node_id: 3

        - name: rf_upper_leg_joint # FRH
          transmission_reduction: *shared_hip_transmission_reduction
          odrive_axis_can_node_id: 6

        - name: rf_lower_leg_joint # FRK
          transmission_reduction: *shared_knee_transmission_reduction
          odrive_axis_can_node_id: 5

        - name: lh_hip_joint # RLS
          transmission_reduction: *shared_splay_transmission_reduction
          odrive_axis_can_node_id: 9

        - name: lh_upper_leg_joint # RLH
          transmission_reduction: *shared_hip_transmission_reduction
          odrive_axis_can_node_id: 12

        - name: lh_lower_leg_joint # RLK
          transmission_reduction: *shared_knee_transmission_reduction
          odrive_axis_can_node_id: 11

        - name: rh_hip_joint # RRS
          transmission_reduction: *shared_splay_transmission_reduction
          odrive_axis_can_node_id: 10

        - name: rh_upper_leg_joint # RRH
          transmission_reduction: *shared_hip_transmission_reduction
          odrive_axis_can_node_id: 8

        - name: rh_lower_leg_joint # RRK
          transmission_reduction: *shared_knee_transmission_reduction
          odrive_axis_can_node_id: 7

